"""backend inheritance

Revision ID: 4dde34190ecd
Revises: acd9f5a6d982
Create Date: 2023-03-28 18:34:11.790352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dde34190ecd'
down_revision = 'acd9f5a6d982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_exists', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('strava_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('strava_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('object_exists')

    # ### end Alembic commands ###
