"""documents added; summary stats removed

Revision ID: 7fa234949c5a
Revises: bffd00e50483
Create Date: 2023-04-06 09:55:33.539657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa234949c5a'
down_revision = 'bffd00e50483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_compressed', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('streams_compressed', sa.BLOB(), nullable=True))
        batch_op.create_foreign_key('strava_fk', 'strava_account', ['import_storage_id'], ['id'])
        batch_op.drop_column('elevation_m')
        batch_op.drop_column('description')
        batch_op.drop_column('tz_local')
        batch_op.drop_column('recorded')
        batch_op.drop_column('elapsed_time_s')
        batch_op.drop_column('moving_time_s')
        batch_op.drop_column('distance_m')
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('distance_m', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('moving_time_s', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('elapsed_time_s', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('recorded', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('tz_local', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('elevation_m', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('strava_fk', type_='foreignkey')
        batch_op.drop_column('streams_compressed')
        batch_op.drop_column('summary_compressed')

    # ### end Alembic commands ###
