"""Add ngp_ms

Revision ID: 2b03e9148ec7
Revises: fe6fd20811ba
Create Date: 2023-01-15 07:30:15.242883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b03e9148ec7'
down_revision = 'fe6fd20811ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngp_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('ngp_ms')

    # ### end Alembic commands ###
