"""IF and TSS calculated props

Revision ID: a41a73892054
Revises: 71dd4ea1073f
Create Date: 2023-01-15 08:01:09.398670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41a73892054'
down_revision = '71dd4ea1073f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('intensity_factor')
        batch_op.drop_column('tss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tss', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('intensity_factor', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
