"""create user settings table with default ftp_ms

Revision ID: acd9f5a6d982
Revises: 236a616b9d9e
Create Date: 2023-01-24 11:16:29.205426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd9f5a6d982'
down_revision = '236a616b9d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_settings_table = op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cp_ms', sa.Float(), server_default=sa.text('(4.12651282051282)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Populate the new table with its (one and only) row
    op.bulk_insert(user_settings_table, [{}])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
